Repository fastbuild/fastbuild, pull requests merged in 2019-11, with the labels that each got.

#657 Add more special characters to XCodeProjectGenerator
  Code/Tools/FBuild/FBuildCore/Helpers/XCodeProjectGenerator.cpp
Labels: Bug

#587 Added a new 'ExecAlwaysShowOutput' option to ExecNode
  Code/Tools/FBuild/FBuildCore/Graph/ExecNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/ExecNode.h
Labels: Enhancement

#616 Require header for CopyDir and RemoveDir
  Code/Tools/FBuild/FBuildCore/BFF/Functions/FunctionCopyDir.cpp
  Code/Tools/FBuild/FBuildCore/BFF/Functions/FunctionCopyDir.h
  Code/Tools/FBuild/FBuildCore/BFF/Functions/FunctionRemoveDir.cpp
  Code/Tools/FBuild/FBuildCore/BFF/Functions/FunctionRemoveDir.h
Labels: Bug

#584 "Database has moved" is not an error anymore - it will trigger a recompile
  Code/Tools/FBuild/FBuildCore/Graph/NodeGraph.cpp
  Code/Tools/FBuild/FBuildTest/Tests/TestGraph.cpp
Labels: Question
