Repository fastbuild/fastbuild, pull requests merged in 2020-02, with the labels that each got.

#586 Create a new FDB when there was an issue parsing the old one
  Code/Tools/FBuild/FBuildCore/Graph/NodeGraph.cpp
Labels: Need More Info (or Blocked), Question

#588 Add option "-nolocalrace"
  Code/Tools/FBuild/FBuildCore/FBuildOptions.cpp
Labels: Need More Info (or Blocked), Question

#636 Periodically update modified time of brokerage files for workers that are still active
  Code/Tools/FBuild/FBuildCore/WorkerPool/WorkerBrokerage.cpp
Labels: Enhancement

#572 Allow FastBuildWorker to clean the broker folder of stale files
  Code/Core/Time/Time.cpp
  Code/Core/Time/Time.h
  Code/Tools/FBuild/FBuildCore/WorkerPool/WorkerBrokerage.cpp
  Code/Tools/FBuild/FBuildCore/WorkerPool/WorkerBrokerage.h
  Code/Tools/FBuild/FBuildWorker/FBuildWorkerOptions.cpp
  Code/Tools/FBuild/FBuildWorker/FBuildWorkerOptions.h
  Code/Tools/FBuild/FBuildWorker/Worker/Worker.cpp
Labels: Enhancement, Need More Info (or Blocked)

#291 Referencing external (non-FASTBuild generated VS projects) in new VSProjectExternal function
  Code/Tools/FBuild/Documentation/docs/functions.html
  Code/Tools/FBuild/Documentation/docs/functions/vsprojectexternal.html
  Code/Tools/FBuild/FBuildCore/BFF/Functions/Function.cpp
  Code/Tools/FBuild/FBuildCore/BFF/Functions/FunctionVSProjectExternal.cpp
  Code/Tools/FBuild/FBuildCore/BFF/Functions/FunctionVSProjectExternal.h
  Code/Tools/FBuild/FBuildCore/FBuild.cpp
  Code/Tools/FBuild/FBuildCore/FBuildCore.bff
  Code/Tools/FBuild/FBuildCore/Graph/Node.cpp
  Code/Tools/FBuild/FBuildCore/Graph/Node.h
  Code/Tools/FBuild/FBuildCore/Graph/NodeGraph.cpp
  Code/Tools/FBuild/FBuildCore/Graph/NodeGraph.h
  Code/Tools/FBuild/FBuildCore/Graph/SLNNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/SLNNode.h
  Code/Tools/FBuild/FBuildCore/Graph/VCXProjectNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/VCXProjectNode.h
  Code/Tools/FBuild/FBuildCore/Graph/VSProjectBaseNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/VSProjectBaseNode.h
  Code/Tools/FBuild/FBuildCore/Graph/VSProjectExternalNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/VSProjectExternalNode.h
  Code/Tools/FBuild/FBuildCore/Helpers/Report.cpp
  Code/Tools/FBuild/FBuildCore/Helpers/SLNGenerator.cpp
  Code/Tools/FBuild/FBuildCore/Helpers/SLNGenerator.h
  Code/Tools/FBuild/FBuildTest/Data/TestProjectGeneration/Solution_ExternalProject/ExternalDummyProject_2.pyproj
  Code/Tools/FBuild/FBuildTest/Data/TestProjectGeneration/Solution_ExternalProject/ExternalDummyProject_3.wixproj
  Code/Tools/FBuild/FBuildTest/Data/TestProjectGeneration/Solution_ExternalProject/ExternalProject.csproj
  Code/Tools/FBuild/FBuildTest/Data/TestProjectGeneration/Solution_ExternalProject/ExternalProjectMissingBraces.csproj
  Code/Tools/FBuild/FBuildTest/Data/TestProjectGeneration/Solution_ExternalProject/fbuild.bff
  Code/Tools/FBuild/FBuildTest/Data/TestProjectGeneration/Solution_ExternalProject/fbuild_WrongData.bff
  Code/Tools/FBuild/FBuildTest/Tests/TestProjectGeneration.cpp
  Code/Tools/FBuild/Integration/FASTBuild.sublime-syntax.txt
  Code/Tools/FBuild/Integration/notepad++markup.xml
  Code/Tools/FBuild/Integration/usertype.dat
  External/VSProjTypeExtractor/VSProjLoaderInterface.h
Labels: Enhancement

#697 VSProjectExternal DLL loading thread safeness
  Code/Tools/FBuild/FBuildCore/Graph/VSProjectExternalNode.cpp
  External/VSProjTypeExtractor/VSProjLoaderInterface.h
Labels: Enhancement

#703 Don't define nullptr
  Code/Core/Env/Types.h
  Code/Core/Process/Thread.cpp
  Code/Tools/FBuild/FBuildCore/Graph/Node.cpp
  Code/Tools/FBuild/FBuildCore/Graph/SLNNode.cpp
Labels: Enhancement

#700 Update bash completion
  Code/Tools/FBuild/Integration/fbuild.bash-completion
Labels: Enhancement

#704 Use Array::EmplaceBack instead of Append where possible
  Code/Core/CoreTest/Tests/TestHash.cpp
  Code/OSUI/OSListView.mm
  Code/Tools/FBuild/FBuildCore/BFF/Functions/Function.cpp
  Code/Tools/FBuild/FBuildCore/BFF/Functions/FunctionCopy.cpp
  Code/Tools/FBuild/FBuildCore/Cache/LightCache.cpp
  Code/Tools/FBuild/FBuildCore/FBuild.cpp
  Code/Tools/FBuild/FBuildCore/FBuildOptions.cpp
  Code/Tools/FBuild/FBuildCore/Graph/CSNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/CopyDirNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/Dependencies.cpp
  Code/Tools/FBuild/FBuildCore/Graph/ExecNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/FileNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/LibraryNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/LinkerNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/NodeGraph.cpp
  Code/Tools/FBuild/FBuildCore/Graph/ObjectListNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/ObjectNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/RemoveDirNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/SLNNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/TestNode.cpp
  Code/Tools/FBuild/FBuildCore/Graph/UnityNode.cpp
  Code/Tools/FBuild/FBuildCore/Helpers/ProjectGeneratorBase.cpp
  Code/Tools/FBuild/FBuildCore/Helpers/Report.cpp
  Code/Tools/FBuild/FBuildCore/Helpers/ToolManifest.cpp
  Code/Tools/FBuild/FBuildCore/Helpers/VSProjectGenerator.cpp
  Code/Tools/FBuild/FBuildCore/WorkerPool/Job.cpp
  Code/Tools/FBuild/FBuildTest/Tests/FBuildTest.cpp
  Code/Tools/FBuild/FBuildTest/Tests/TestBuildFBuild.cpp
  Code/Tools/FBuild/FBuildTest/Tests/TestCompilationDatabase.cpp
  Code/Tools/FBuild/FBuildTest/Tests/TestExec.cpp
  Code/Tools/FBuild/FBuildTest/Tests/TestGraph.cpp
  Code/Tools/FBuild/FBuildTest/Tests/TestNodeReflection.cpp
Labels: Enhancement
